FROM alpine:3.7

ENV APP_DIR=/srv/app

RUN mkdir -p $APP_DIR
WORKDIR $APP_DIR

RUN apk add --update --no-cache git gcc libc-dev python3 python3-dev jpeg-dev zlib-dev
ENV LIBRARY_PATH=/lib:/usr/lib

COPY requirements.txt .
RUN pip3 --no-cache-dir install -r requirements.txt
