# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-09-08 20:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='episode',
            name='digas_broadcast_id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='digas_show_id',
        ),
        migrations.RemoveField(
            model_name='episode',
            name='podcast_url',
        ),
        migrations.RemoveField(
            model_name='show',
            name='digas_show_id',
        ),
        migrations.AlterField(
            model_name='episode',
            name='on_demand_url',
            field=models.URLField(help_text='http://hemingway.radiorevolt.no/ondemandinfo/'),
        ),
        migrations.AlterField(
            model_name='post',
            name='show',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='posts', to='data_models.Show'),
        ),
    ]
