# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-24 22:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_auto_20160908_2200'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='on_demand_url',
            field=models.URLField(help_text='https://ondemandinfo.radiorevolt.no/'),
        ),
    ]
