# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 18:47
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0002_auto_20160908_2200'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='use_title',
            field=models.BooleanField(default=False, help_text='Vis tittelen på episoden. Om ikke tittel benyttes vises "Navn på show" + "Publiseringsdato"', verbose_name='Bruk tittel'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Opprettet av'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='lead',
            field=models.CharField(max_length=140, verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='on_demand_url',
            field=models.URLField(help_text='https://ondemandinfo.radiorevolt.no/'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='show',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='episodes', to='data_models.Show', verbose_name='Program'),
        ),
        migrations.AlterField(
            model_name='episode',
            name='title',
            field=models.CharField(max_length=64, verbose_name='Tittel'),
        ),
    ]
