# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-10-30 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0003_auto_20171024_2242'),
        ('data_models', '0003_auto_20171030_1847'),
    ]

    operations = [
    ]
