# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 19:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0004_merge_20171030_1911'),
    ]

    operations = [
        migrations.AddField(
            model_name='episode',
            name='publish_at',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
