# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-01 16:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0006_model_translations_20171101_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='categories',
            field=models.ManyToManyField(blank=True, to='data_models.Category', verbose_name='Kategorier'),
        ),
        migrations.AlterField(
            model_name='post',
            name='categories',
            field=models.ManyToManyField(blank=True, to='data_models.Category', verbose_name='Kategorier'),
        ),
        migrations.AlterField(
            model_name='show',
            name='categories',
            field=models.ManyToManyField(blank=True, to='data_models.Category', verbose_name='Kategorier'),
        ),
    ]
