# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-02 20:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0005_episode_publish_at'),
        ('data_models', '0007_blank_categories_20171101_1638'),
    ]

    operations = [
    ]
