# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-05 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0008_post_episodes'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='episode',
            options={'ordering': ['-created_at'], 'verbose_name': 'Episode', 'verbose_name_plural': 'Episoder'},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-publish_at'], 'verbose_name': 'Artikkel', 'verbose_name_plural': 'Artikler'},
        ),
        migrations.AlterField(
            model_name='post',
            name='episodes',
            field=models.ManyToManyField(blank=True, help_text='Legger til episoder i bunnen av artikkelen. Episodelisten blir filtrert på valgt program etter at artikkelen er opprettet.', to='data_models.Episode', verbose_name='Episoder'),
        ),
    ]
