# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-11-13 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0008_merge_20171102_2019'),
        ('data_models', '0009_auto_20171105_1507'),
    ]

    operations = [
    ]
