# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2018-01-31 16:19
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0010_merge_20171113_2120'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=sorl.thumbnail.fields.ImageField(upload_to='uploads/images', verbose_name='Bilde'),
        ),
    ]
