# Generated by Django 2.0.2 on 2018-02-24 15:44

from django.db import migrations
import sorl_cropping.fields


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0011_post_cropping'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='cropping',
            field=sorl_cropping.fields.ImageRatioField(blank=True, help_text='Velg bildeutsnitt', image_field='image', max_length=255, size='1024x512', verbose_name='Bildeutsnitt'),
        ),
    ]
