# Generated by Django 2.0.2 on 2018-09-17 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0012_auto_20180224_1644'),
    ]

    operations = [
        migrations.CreateModel(
            name='Settings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('about', models.TextField(verbose_name='Om Radio Revolt')),
            ],
            options={
                'verbose_name': 'Innstillinger',
            },
        ),
    ]
