# Generated by Django 2.0.2 on 2018-09-29 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0014_post_ready_to_be_published'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='chief_editor',
            field=models.CharField(default='', max_length=128, verbose_name='Ansvarlig redaktør'),
        ),
        migrations.AddField(
            model_name='settings',
            name='radio_editor',
            field=models.CharField(default='', max_length=128, verbose_name='Radioredaktør'),
        ),
    ]
