# Generated by Django 2.0.2 on 2018-10-01 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0015_editors_in_settings'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='privacy_policy',
            field=models.TextField(default='', verbose_name='Personvernerklæring'),
        ),
    ]
