# Generated by Django 2.0.12 on 2019-02-17 22:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0019_longer_titles'),
    ]

    operations = [
        migrations.AddField(
            model_name='settings',
            name='music_producer',
            field=models.CharField(default='', max_length=128, verbose_name='Musikkprodusent'),
        ),
    ]
