# Generated by Django 2.0.12 on 2019-03-18 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0020_settings_music_producer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='episode',
            name='lead',
            field=models.TextField(verbose_name='Beskrivelse'),
        ),
        migrations.AlterField(
            model_name='show',
            name='lead',
            field=models.TextField(max_length=255, verbose_name='Kort beskrivelse'),
        ),
    ]
