# Generated by Django 2.0.12 on 2019-03-25 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0021_more_textfields'),
    ]

    operations = [
        migrations.CreateModel(
            name='HighlightedPost',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('posts', models.ManyToManyField(blank=True, help_text='Legg til artikler som skal fremheves på forsiden. Maksimalt 5 artikler.<br>Dukker ikke artikkelen opp? Har du husket å markere den som "Klar til publisering"?<br>', limit_choices_to={'ready_to_be_published': True}, to='data_models.Post', verbose_name='Artikler')),
            ],
            options={
                'verbose_name': 'Fremhevede artikler',
            },
        ),
    ]
