# Generated by Django 2.0.12 on 2019-04-28 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0022_highlightedpost'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='digas_id',
            field=models.IntegerField(null=True, unique=True, verbose_name='Tilhørende Digas-program'),
        ),
    ]
