# Generated by Django 2.0.12 on 2019-04-28 14:10

from django.db import migrations
import requests


def populate_digas_id(apps, schema_editor):
    Show = apps.get_model('data_models', 'Show')
    digas_id_by_on_demand_link = get_digas_id_by_on_demand_link()

    for show in Show.objects.all():
        # Skip entries with ID already, they may have been set manually by users
        if show.digas_id:
            continue

        max_tries = 15
        for i in range(max_tries):
            try:
                episode = show.episodes.all()[i]
            except IndexError:
                # Just finish the loop without breaking, triggering error msg
                continue

            if not episode.on_demand_url:
                # Try next
                continue

            sod_url = episode.on_demand_url
            if sod_url not in digas_id_by_on_demand_link:
                # Maybe the next one is recognized
                continue

            # We found something!
            show.digas_id = digas_id_by_on_demand_link[sod_url]
            show.save()
            # Break out of this inner for loop, continuing with next show
            break
        else:
            # We never found a satisfying episode, warn user about this
            print(
                'No suitable episode was found for "{show}"'
                .format(show=show.name)
            )


def get_digas_id_by_on_demand_link():
    r = requests.get('https://api.radiorevolt.no/v2/lyd/ondemand/')
    r.raise_for_status()
    data = r.json()

    return {e['url']: e['program_defnr'] for e in data}


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0023_show_digas_id'),
    ]

    operations = [
        migrations.RunPython(
            # Populate Digas ID when going forward
            populate_digas_id,
            # We don't know what is supplied by user and what is from us, so
            # don't do anything when undo-ing this migration (it's idempotent)
            migrations.RunPython.noop
        )
    ]
