# Generated by Django 2.0.12 on 2019-04-29 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0025_show_is_podcast'),
    ]

    operations = [
        migrations.AddField(
            model_name='show',
            name='podcast_url',
            field=models.CharField(default=None, editable=False, max_length=100, null=True, verbose_name='Podkast-URL'),
        ),
    ]
