# Generated by Django 2.0.12 on 2019-04-29 15:24
import logging

from django.db import migrations

from data_models.rr_api import get_podcast_url_from_digas_id

log = logging.getLogger(__name__)


def update_podcast_url(apps, schema_editor):
    Show = apps.get_model('data_models', 'Show')

    for show in Show.objects.all():
        # The following code is copied over from models.py. This is because
        # custom methods are not available to us here in a migration. See
        # https://docs.djangoproject.com/en/2.1/topics/migrations/#historical-models
        if show.digas_id is not None:
            try:
                show.podcast_url = get_podcast_url_from_digas_id(show.digas_id)
            except Exception:
                log.exception(
                    'Error occurred while trying to update podcast_url for {}. '
                    'Not updating podcast_url this time.'.format(show.name)
                )
        else:
            show.podcast_url = None
        show.save()


class Migration(migrations.Migration):

    dependencies = [
        ('data_models', '0026_show_podcast_url'),
    ]

    operations = [
        migrations.RunPython(
            # Ensure podcast_url is updated when going forward
            update_podcast_url,
            # We are simply working around the fact that save() is not run when
            # adding a DB field. Undoing that is not possible, but should not
            # pose a problem
            migrations.RunPython.noop
        )
    ]
